cnpm/cnpmjs.org

config/index.js, middleware/auth.js, servers/registry.js, test/middleware/auth.test.js
Add `alwaysAuth: true` to config and set npm cli config.
Use 'http://registry.sample.com' for example, set npm config below:
$ npm config set '//registry.sample.com/:always-auth=true'
$ npm login --registry=http://registry.sample.com
$ npm install mocha --registry=http://registry.sample.com
Fixes #600
=> feat: support always-auth

controllers/registry/package/list.js
只用这个表的 modifiedTime 做 etag 不对，在 unpublish 的时候会先修改这张表的数据，然后调用一次 list，再删除 tag 和文件，导致缓存了一个 etag 和最终的 etag 一致，但是内容不一致
=> fix(list): let koa-etag to caculate the etag

controllers/registry/package/show.js, routes/registry.js, services/package.js, test/controllers/registry/package/list.test.js, test/controllers/registry/package/show.test.js, test/controllers/web/package/show.test.js, test/services/package.test.js
e.x. `/npm/~1.0.0`
closes #814
=> feat: support semver

.travis.yml, sync/sync_exist.js
=> fix: don't sync constructor package on exists mode

public/css/github-markdown.css
http://cnpmjs.org/package/fms 
自动生成数据文档章节的 pre 标签 color 值使用了 main.css 的 `color: #fff;`
=> fix: http://cnpmjs.org/package/fms pre style

config/index.js
for https://github.com/cnpm/cnpmjs.org/issues/925
=> userService

.travis.yml, LICENSE.txt, Makefile, controllers/registry/package/list.js, middleware/proxy_to_npm.js, middleware/sync_by_install.js, test/controllers/registry/module/scope_package.test.js, test/controllers/sync_module_worker.test.js, test/init.js, test/init_db.js, test/middleware/proxy_to_npm.test.js, test/middleware/sync_by_install.test.js
=> fix: should sync missing public scoped package on install

common/logger.js, config/index.js, controllers/sync_module_worker.js, controllers/total.js, dispatch.js, package.json, sync/changes_stream_syncer.js, sync/index.js, sync/status.js, sync/sync_all.js, sync/sync_exist.js, sync/sync_popular.js, sync/sync_since.js
fix scope package missing problem
close #908
=> feat: add changes stream syncer

services/package.js
=> fix: getModuleByRange don't list all packages

sync/index.js
and skip JSONResponseFormatError and 504 server error
=> fix: limit sync fails email notice

controllers/sync_module_worker.js
closes https://github.com/cnpm/cnpmjs.org/issues/1066
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/cnpmjs.org/1067)
=> fix: ignore long package name on unpublished sync

bin/cli.js
首先，cnpmjs.org很棒，感谢cnpm团队！
我是通过全局安装npmjs.org模块方式部署的，所以就需要通过`cnpmjs.org start/stop`启动/停止服务，经排查，原因是：
bin/cli.js的`stop`方法中的treekill为异步方法，而在`start`方法中是同步调用`stop`的，导致传入的回调(删除pid文件)几乎必然(递归杀进程)比`start`方法中的『写入pid操作』要晚，最终的结果是，服务起来了，但是pid文件丢失了。
而通过源码部署，`npm start`调用的是shell脚本，而且是通过`ps ax`查询进程号，没有异步的过程，所以没有问题。
现已将`stop`方法改为返回Promise，解决此问题。
请考虑合并~
=> 修复『全局命令cnpmjs.org stop不稳定』问题

config/index.js, controllers/sync_module_worker.js
avoid https://github.com/npm/registry/issues/255 again
=> feat: can config to not sync deleted versions

docs/db.sql, models/download_total.js, models/module.js, models/module_abbreviated.js, models/module_deps.js, models/module_keyword.js, models/module_log.js, models/module_maintainer.js, models/module_star.js, models/module_unpublished.js, models/npm_module_maintainer.js, models/package_readme.js, models/tag.js, models/total.js, models/user.js
Some points:
+ let module name be 214. ([refer](https://docs.npmjs.com/files/package.json#name))
+ indexes (docs/db.sql only):
- let uniq indexes starts with `uk_`;
- let other indexes starts with `idx_`;
> Because sqlite's index namespace is the whole database, two tables can't have the same index name. I didn't add the index names to models/*.js.
=> refactor: normalize database structure

controllers/web/package/show.js, routes/web.js, test/controllers/web/package/show.test.js, test/controllers/web/show_sync.test.js
e.g.
https://NPMHOST/package/@scope/name/v/1.7.1-beta-46
=> fix: show package when non-semver version of semver tag

middleware/proxy_to_npm.js, test/middleware/proxy_to_npm.test.js
when use cnpm building private repository, and use yarn or npm to install public scoped package like @types/node, yarn or npm will emit following url with encoded path
https://registry.npm.company.com/@types%2fnode
currently, cnpm won't proxy to source repositry.
this pull request is try to resolve this issue.
=> fix proxy to source when package is public scoped with encoded path

README.md
README fix typo ( not to use plural for code ):
code 
not 
codes
=> README fix typo ( not to use plural for code )

docs/dockerize/config.js
修复docker构建配置中fs-cnpm的初始化问题。 #1657
=> fix: fs-cnpm on dockerize config

services/npm.js, sync/sync_exist.js, test/sync/sync_exist.test.js
closes https://github.com/cnpm/cnpmjs.org/issues/1704
=> refactor: Sync exists package from cnpmcore changes stream

.github/workflows/nodejs.yml, config/index.js, services/package.js, test/controllers/registry/package/changes.test.js, test/services/package.test.js
* 新增 changesDelay 配置，调用 /-/all/changes 接口时默认返回 delay 之前的 changes
* 防止出现 since 和当前时间接近时，changes 异步插入，导致 changes 计算失败的问题
=> add changes delay

controllers/registry/package/download.js
> 包名超长时，更新下载记录接口会无限重试
* 更新下载记录前，先判断当前包名是否存在
-------------
> When the package name is too long, the update download record interface will retry indefinitely.
* Check pkg exists, before updating the download record.
=> fix: download row create error
